paths:
  /products:
    get:
      summary: Get products
      tags:
        - Products
      parameters:
        - name: limit
          in: query
          description: Number of products per page (default:10)
          schema:
            type: integer
            example: 10
        - name: page
          in: query
          description: Page number (default:1)
          schema:
            type: integer
            example: 1
        - name: query
          in: query
          description: Filtering criteria in JSON format
          schema:
            type: string
            example: '{"category": "Electronics"}'
        - name: sort
          in: query
          description: Sorting order (default:null)
          schema:
            type: integer
            example: 1
      responses:
        '200':
          description: List of products retrieved successfully
        '500':
          description: Internal server error

  /products/{pid}:
    get:
      summary: Get product by ID
      tags:
        - Products
      parameters:
        - name: pid
          in: path
          description: ID of the product to retrieve
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Product retrieved successfully
        '404':
          description: Product not found
        '500':
          description: Internal server error

    put:
      summary: Update product
      tags:
        - Products
      parameters:
        - name: pid
          in: path
          description: ID of the product to update
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        '200':
          description: Product updated successfully
        '403':
          description: Forbidden - User does not have permission to update this product
        '404':
          description: Product not found
        '500':
          description: Internal server error

    delete:
      summary: Delete product
      tags:
        - Products
      parameters:
        - name: pid
          in: path
          description: ID of the product to delete
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Product deleted successfully
        '403':
          description: Forbidden - User does not have permission to delete this product
        '404':
          description: Product not found
        '500':
          description: Internal server error

  /products/addproduct:
    post:
      summary: Add a new product
      tags:
        - Products
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        '201':
          description: Product added successfully
        '400':
          description: Bad request - Missing required parameters
        '403':
          description: Forbidden - User does not have permission to add a product
        '409':
          description: Conflict - Product with the same code already exists
        '500':
          description: Internal server error

components:
  schemas:
    Product:
      type: object
      properties:
        _id: 
          type: ObjectId
          description: MongoDB autogenerated id
        title:
          type: string
          example: Smartphone
        description:
          type: string
          example: Latest smartphone model
        price:
          type: number
          example: 999.99
        code:
          type: string
          example: ABC123
        stock:
          type: integer
          example: 100
        category:
          type: string
          example: Electronics
        thumbnails:
          type: array
          items:
            type: string
          example: ["thumbnail1.jpg", "thumbnail2.jpg"]